// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
//! Always load dotenv first

import "dotenv/config";
import { defineConfig } from "prisma/config";
import { env } from "./src/lib/env";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env.DATABASE_URL,
  },
});
